// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package ports

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for UserRole.
const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
	UserRoleUser      UserRole = "user"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// User defines model for User.
type User struct {
	Followers        int64     `json:"followers"`
	Following        int64     `json:"following"`
	Id               int64     `json:"id"`
	Karma            int64     `json:"karma"`
	LastLogin        time.Time `json:"lastLogin"`
	Name             string    `json:"name"`
	PostsCount       int64     `json:"postsCount"`
	RegistrationDate time.Time `json:"registrationDate"`
	Role             UserRole  `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserArray defines model for UserArray.
type UserArray = []User

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = Error

// UserData defines model for UserData.
type UserData = User

// UserFollowers defines model for UserFollowers.
type UserFollowers = UserArray

// UserFollows defines model for UserFollows.
type UserFollows = UserArray
